trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo "Running CI for PR"
